import type { AirtableTableConfig } from "../types/integrations";

export const AIRTABLE_BASE_NAMES = [
  "AMA MOB OS V2",
  "Shakti System OS",
  "Shakti Shala Vault",
] as const;

export const AIRTABLE_TABLES = {
  seekers: {
    name: "Seekers",
    purpose: "Track people moving through the Shakti pathway.",
    fields: [
      "Seeker ID",
      "Full Name",
      "Email",
      "Phone",
      "Location",
      "Timezone",
      "Current Access Level",
      "Current Readiness Stage",
      "Current Pathway",
      "Pathway Day",
      "Community Status",
      "Retreat Interest",
      "Retreat Readiness Score",
      "Last Active Date",
      "Notes",
      "Human Review Needed",
      "Created At",
      "Updated At",
    ],
    options: {
      "Current Access Level": [
        "Visitor",
        "Seeker",
        "Practitioner",
        "Initiate",
        "Temple Circle",
        "Guide",
        "Teacher",
      ],
      "Current Readiness Stage": [
        "Exploring",
        "Oriented",
        "Practicing",
        "Ready for Circle",
        "Retreat Interested",
        "Retreat Applicant",
        "Accepted",
        "Preparing",
        "Integrated",
      ],
    },
  },
  libraryAssets: {
    name: "Library Assets",
    purpose: "Metadata layer for all source content in the Temple Library.",
    fields: [
      "Asset ID",
      "Title",
      "Description",
      "Drive URL",
      "Source Folder",
      "Media Type",
      "File Type",
      "Creator",
      "Owner",
      "Date Created",
      "Date Uploaded",
      "Theme",
      "Keywords",
      "Goddess / Archetype",
      "Moon Phase",
      "Practice Type",
      "Container / Offer",
      "Access Level",
      "Readiness Level",
      "Retreat Relevance",
      "Transcript Status",
      "AI Summary Status",
      "Publishing Status",
      "Confidentiality",
      "Usage Rights",
      "Related Assets",
      "Related Practice",
      "Related Pathway",
      "Related Retreat",
      "Notes",
    ],
    options: {
      "Media Type": [
        "PDF",
        "Audio",
        "Video",
        "Image",
        "Document",
        "Slide Deck",
        "Transcript",
        "Worksheet",
        "Journal Prompt",
        "Ceremony Guide",
        "Retreat Guide",
        "Other",
      ],
      "Publishing Status": [
        "Raw",
        "Needs Review",
        "Needs Transcript",
        "Needs Summary",
        "Ready To Tag",
        "Approved",
        "Published",
        "Archived",
      ],
    },
  },
  practices: {
    name: "Practices",
    purpose: "Track practices that appear inside the app.",
    fields: [
      "Practice ID",
      "Title",
      "Short Description",
      "Full Description",
      "Duration",
      "Practice Type",
      "Associated Goddess",
      "Associated Moon Phase",
      "Access Level",
      "Readiness Level",
      "Audio URL",
      "Video URL",
      "Worksheet URL",
      "Transcript URL",
      "Related Library Assets",
      "Completion Prompt",
      "Integration Prompt",
      "Status",
      "Notes",
    ],
    options: {
      "Practice Type": [
        "Somatic",
        "Breath",
        "Meditation",
        "Shadow Work",
        "Journal",
        "Ceremony",
        "Kriya",
        "Pranayama",
        "Grounding",
        "Integration",
        "Retreat Prep",
      ],
    },
  },
  goddessPathways: {
    name: "Goddess Pathways",
    purpose:
      "Map each chamber and its associated teachings, practices, and access rules.",
    fields: [
      "Pathway ID",
      "Goddess / Archetype",
      "Display Name",
      "Core Theme",
      "Energetic Blueprint",
      "Recommended Practices",
      "Recommended Journal Prompts",
      "Access Level",
      "Readiness Notes",
      "Moon Phase Alignment",
      "Retreat Alignment",
      "Visual Atmosphere Notes",
      "Status",
    ],
  },
  initiationKeys: {
    name: "Initiation Keys",
    purpose: "Track access products, credentials, and symbolic passage.",
    fields: [
      "Key ID",
      "Key Name",
      "Access Level Granted",
      "Offering Amount",
      "Payment Type",
      "Physical Object Included",
      "Description",
      "Eligibility Notes",
      "Stripe Product ID",
      "Stripe Price ID",
      "Active",
      "Notes",
    ],
    options: {
      "Key Name": [
        "Seeker Key",
        "Practitioner Key",
        "Initiate Key",
        "Temple Circle Key",
        "Retreat Passage Key",
        "Guide Key",
        "Teacher Key",
      ],
      "Payment Type": [
        "Free",
        "One-Time Offering",
        "Monthly Stewardship",
        "Annual Stewardship",
        "Retreat Deposit",
        "Invitation Only",
        "Manual Approval",
      ],
    },
  },
  offerings: {
    name: "Offerings",
    purpose: "Track payments, pledges, access purchases, and stewardship events.",
    fields: [
      "Offering ID",
      "Seeker",
      "Key / Access Item",
      "Amount",
      "Currency",
      "Payment Status",
      "Stripe Payment ID",
      "Stripe Customer ID",
      "Date",
      "Access Granted",
      "Notes",
    ],
    options: {
      "Payment Status": [
        "Pending",
        "Completed",
        "Failed",
        "Refunded",
        "Manually Approved",
      ],
    },
  },
  environmentalMemory: {
    name: "Environmental Memory",
    purpose: "Future cloud-sync layer for sanctuary memory.",
    fields: [
      "Memory ID",
      "Seeker",
      "Memory Type",
      "Room",
      "Value",
      "Date Created",
      "Last Updated",
      "Related Practice",
      "Related Offering",
      "Related Journal Entry",
      "Notes",
    ],
    options: {
      "Memory Type": [
        "Prayer Lamp",
        "Prayer Flag",
        "Daily Offering",
        "Cedar Growth",
        "Lotus Bloom",
        "Bird Returned",
        "Lantern Cycle",
        "Stillness Hours",
        "Fire Intention",
        "Moon Star",
      ],
    },
  },
  retreats: {
    name: "Retreats",
    purpose:
      "Track retreat opportunities, applications, readiness, and preparation.",
    fields: [
      "Retreat ID",
      "Retreat Name",
      "Location",
      "Start Date",
      "End Date",
      "Capacity",
      "Status",
      "Application URL",
      "Deposit Amount",
      "Full Price",
      "Preparation Start Date",
      "Required Practices",
      "Required Materials",
      "Notes",
    ],
    options: {
      Status: [
        "Idea",
        "Planning",
        "Open Interest",
        "Applications Open",
        "Reviewing",
        "Confirmed",
        "Full",
        "Completed",
        "Archived",
      ],
    },
  },
  retreatApplications: {
    name: "Retreat Applications",
    purpose: "Human-reviewed retreat readiness pipeline.",
    fields: [
      "Application ID",
      "Seeker",
      "Retreat",
      "Application Date",
      "Readiness Score",
      "Body Readiness",
      "Emotional Readiness",
      "Logistics Readiness",
      "Financial Readiness",
      "Review Status",
      "Reviewer Notes",
      "Accepted Date",
      "Deposit Status",
      "Preparation Status",
    ],
    options: {
      "Review Status": [
        "Submitted",
        "Needs Review",
        "Follow Up Needed",
        "Accepted",
        "Waitlisted",
        "Not Yet",
        "Declined",
      ],
    },
  },
  contentQueue: {
    name: "Content Queue",
    purpose:
      "Turn Vault material into publishable content without losing lineage sensitivity.",
    fields: [
      "Content ID",
      "Title",
      "Source Asset",
      "Content Type",
      "Platform",
      "Theme",
      "Audience",
      "Status",
      "Draft URL",
      "Published URL",
      "Review Needed",
      "Lineage Sensitivity Notes",
      "Publish Date",
      "Owner",
    ],
    options: {
      Status: [
        "Idea",
        "Drafting",
        "Needs Review",
        "Approved",
        "Scheduled",
        "Published",
        "Archived",
      ],
    },
  },
} as const satisfies Record<string, AirtableTableConfig>;

export const AIRTABLE_INITIAL_BUILD_PRIORITY = [
  AIRTABLE_TABLES.seekers.name,
  AIRTABLE_TABLES.libraryAssets.name,
  AIRTABLE_TABLES.practices.name,
  AIRTABLE_TABLES.initiationKeys.name,
  AIRTABLE_TABLES.retreats.name,
  AIRTABLE_TABLES.retreatApplications.name,
  AIRTABLE_TABLES.environmentalMemory.name,
] as const;

export const AIRTABLE_SECONDARY_BUILD_PRIORITY = [
  AIRTABLE_TABLES.goddessPathways.name,
  AIRTABLE_TABLES.offerings.name,
  AIRTABLE_TABLES.contentQueue.name,
] as const;
